language: rust
cache:
  apt: true
  directories:
  - target/debug/deps
  - target/debug/build
script:
- cargo build --verbose
- cargo test --verbose
- cargo doc --no-deps
after_success: |
  [ $TRAVIS_RUST_VERSION = stable ] &&
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
  ls target/debug &&
  ./kcov-master/tmp/usr/local/bin/kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/flaken-* &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  { [ "$TRAVIS_TAG" != "" ] || [ "$TRAVIS_BRANCH" == "master" ]; } &&
  cargo doc --no-deps &&
  ./.travis/docs.sh &&
  echo "\nDocs published.\n"
notifications:
  email: true
env:
  global:
    secure: fUh3hPNIlAseGL3qs84zYmbKeQzaKcIYJHC6GFYnaRenB5SlVBNXvBG/WG3ST6XyMlAMpREIhDSZJasElYlMrdOQRXtxnqebeYBVapTQXQBgNBe5wb/q8SUBHuoWyYvoN7Ql+Pu3Vri+LKT+hnHV7ctHgE8sWPtUjrjz4b9eG/0Hy20I4yaDp0O8NpGhM8sUfJCACujTEmih2k58mt61XUNnZuIrm1h+x8gxDCg9PSg9fk1s/hF7Km3PFH8kBF2moYua9k7YTJ2tHKmrWDdC9nFMlyd2JRcfi2aIaT7NEclPjw/IWlLpynDT5tOWxfcuKybVJOlDQ1qdUsyX9OsctN1S9bIAnbsXNKeWOwgnxZlMFCXdtrCb76/D4F+EaoAHY4RD0s5Xqqp85H6LCuQIvxLymDWbi7hCtR4IccfwBsq63os2cDYFhqVoEzn1VMpvK7hShwm+QVETgqmB1h3vWalcSl/JOlZG+c65X5M7RK6Ed9GbIKomecvV8/pcAq+hdRBJmglKQ+aUsc3d3wM8Gd8ePp5/YYGLop5vK7f+ELkqxV4T4FXYHlm8UVQnSKBKc334rTh+oRkzGpQ5YvYrYlwMu4j132+/QG/eiXj42DWWIEP8V0kSgBgyVMVEoQaFYZWyG5URcHr9RvLqVTCyaUZ+J2eYUl4Qzdl+flVUrcw=
