[package]
name = "monteflake"
description = "Configurable bitwidth snowflake id generator, encoder, decoder"
license = "MIT"
repository = "https://github.com/bfrog/monteflake"
version = "1.0.0"
authors = ["Tom Burdick <thomas.burdick@gmail.com>"]
keywords = ["snowflake", "flake", "id", "monte"]
