[package]
name = "monteflake"
description = "Use https://crates.io/crates/flaken instead"
license = "MIT"
repository = "https://github.com/bfrog/monteflake"
version = "0.1.3"
authors = ["Tom Burdick <thomas.burdick@gmail.com>"]
keywords = []

[dependencies]
